### ISSUE TITLE
Seems like order of fields in ConstrainStepSize constructor is inappropriate

### ISSUE THREAD

**Issue by stepanzh** [vvpisarev/Downhill.jl#24]
I try to migrate in CubicEoS from DescentMethods to Downhill.

I use the following call

```julia
result = Downhill.optimize!(Dfunc!, optmethod, η_;
    gtol=1e-3,
    maxiter=1000,
    constrain_step=maxstep,
    reset=false,
)
```

but getting an error

```julia
ERROR: LoadError: MethodError: no method matching Downhill.ConstrainStepSize(::Downhill.LimitCalls{Downhill.LimitIters{Downhill.StopByGradient{Downhill.CholBFGS{Float64, Vector{Float64}, LinearAlgebra.Cholesky{Float64, Matrix{Float64}}}, Float64}}}, ::CubicEoS.var"#stability_step#41"{Vector{Float64}})
Closest candidates are:
  Downhill.ConstrainStepSize(::Downhill.AbstractOptBuffer) at /Users/stepanzh/.julia/packages/Downhill/AFZHq/src/wrappers.jl:188
  Downhill.ConstrainStepSize(::F, ::T) where {F, T<:Downhill.AbstractOptBuffer} at /Users/stepanzh/.julia/packages/Downhill/AFZHq/src/wrappers.jl:184
```

Seem like caused by this call

https://github.com/vvpisarev/Downhill.jl/blob/968d10a382d70fcf962b41400824706ce251fe98/src/optimize.jl#L126-L128

whereas the definition is

https://github.com/vvpisarev/Downhill.jl/blob/968d10a382d70fcf962b41400824706ce251fe98/src/wrappers.jl#L183-L188

So, there is a misorder of arguments.

Also, I guess the 2nd constructor of `ConstrainStep` is opaque. You may have a single constructor with default step set to `Downhill.infstep`.

I tried to change the fields' order to

```julia
struct ConstrainStepSize{F, T<:AbstractOptBuffer} <: Wrapper
    descent::T
    constraint::F
end

ConstrainStepSize(M::AbstractOptBuffer) = ConstrainStepSize(M, infstep)
```

and seems like it is work. But I isn't certain about this order.

**Comment by vvpisarev** [comment]
My idea is to keep the general agreement that function argument comes first if one is present, so the issue must be fixed on call sites (in `optimize` and `solver`).
