### ISSUE TITLE
Support of custom stop condition

### ISSUE THREAD

**Issue by stepanzh** [vvpisarev/Downhill.jl#29]
I guess, it should be a function that takes 
- argument;
- (maybe) gradient;
   Gradient may be calculated from the argument by user.
- (maybe) argument step (dx = xnew - xold);
   Can't be calculated by user, but usually dx is needed for stopping like `norm(dx) <= eps`, which seems for me as a wrapper `StopByStep`, also is it a default stopping criterion?

Example

```julia
convcond(x) = maximum(abs.(x)) <= 1e-6
Downhill.optimize!(...; convcond=convcond, ...)
```

**Comment by vvpisarev** [comment]
Can be done by modifying `BasicConvergenceStats` wrapper from the `basic_wrapper` branch in the following way:
1. Add a callback field to store the custom convergence callback
2. The callback must have a signature `(current_x, previous_x, current_f, previous_f, gradient) -> Bool`
3. To keep the continuity, the default callback could be checking the gradient against the predefined tolerance
4. It's better to store the result of the convergence check in a field of `BasicConvergenceStats` to avoid repeated calls in `stopcond` and `conv_success`

All basic methods have to implement current and previous argument and function values.
